

<footer>
    <p>Copyright © <?= date('Y'); ?></p>
</footer>

<div id="scripts">
    <script src="/vendor/components/jquery/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
    <script src="/public/js/messages_ru.min.js"></script>
    <script src="/public/js/validate.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="/vendor/twbs/bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="/public/js/admin/articles.js"></script>
    <script src="/public/js/admin/cars.js"></script>
    <script src="/public/js/admin/user.js"></script>
    <script src="/public/js/admin/reviews.js"></script>
    <script src="/public/js/admin/categories.js"></script>
    <script src="/public/js/go_top.js"></script>
    <?php $uri = explode('/', $_SERVER['REQUEST_URI']); ?>
    <?php if (isset($uri[2])): ?>
        <?php switch ($uri[2]):
            case 'articles':
                print '<script> var deleteUri = \'/delete/article\'</script>';
                print '<script src="/public/js/admin/delete.js"></script>';
                print '<script src="/public/js/admin/update/articles.js"></script>';
                break;
            case 'categories':
                print '<script src="/public/js/admin/update/categories.js"></script>';
                print '<script> var deleteUri = \'/delete/category\';</script>';
                print '<script src="/public/js/admin/delete.js"></script>';
                break;
            case 'cars':
                print '<script src="/public/js/admin/update/cars.js"></script>';
                print '<script src="/public/js/admin/delete/cars.js"></script>';
                break;
            case 'reviews':
                print '<script> var deleteUri = \'/delete/review\';</script>';
                print '<script src="/public/js/admin/delete.js"></script>';
                break;
            case 'users':
                print '<script src="/public/js/admin/update/users.js"></script>';
                break;
        endswitch; ?>
    <?php endif; ?>
</div>

</body>
</html>