<?php $uri = explode('/', $_SERVER['REQUEST_URI']); ?>
<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>
        <?php if (! empty($page)): ?>
            <?= htmlentities($page->title); ?>
        <?php endif; ?>
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="/public/css/admin.css">
</head>
<body>
<div class="nav-container">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <nav class="nav nav-pills flex-column flex-sm-row">
                    <a class="flex-sm-fill text-sm-center nav-link main-link" href="/">АвтоБлог</a>
                    <a class="flex-sm-fill text-sm-center nav-link
                        <?php if (! isset($uri[2])) {print 'active';} ?>
                    " href="/admin">Главная</a>
                    <a class="flex-sm-fill text-sm-center nav-link
                        <?php if (isset($uri[2]) && $uri[2] === 'articles') {print 'active';} ?>
                    " href="/admin/articles">Статьи</a>
                    <a class="flex-sm-fill text-sm-center nav-link
                        <?php if (isset($uri[2]) && $uri[2] === 'cars') {print 'active';} ?>
                    " href="/admin/cars">Авто</a>
                    <a class="flex-sm-fill text-sm-center nav-link
                        <?php if (isset($uri[2]) && $uri[2] === 'reviews') {print 'active';} ?>
                    " href="/admin/reviews">Отзывы</a>
                    <a class="flex-sm-fill text-sm-center nav-link
                        <?php if (isset($uri[2]) && $uri[2] === 'users') {print 'active';} ?>
                    " href="/admin/users">Пользователи</a>
                </nav>
            </div>
            <div class="col-sm-4">
                <div class="welcome">
                    <div class="admin">Добро пожаловать, <?= htmlentities(mb_ucfirst(\IhorRadchenko\App\Components\Session::get('user')->f_name)); ?></div>
                    <a href="/logout">Выйти</a>
                </div>
            </div>
        </div>
    </div>
</div>

<header>
    <div class="container">
        <div class="row">
            <div class="col-sm-10">
                <h1 class="header-title">
                    <i class="fa fa-cog" aria-hidden="true"></i>
                    <span>Dashboard</span>
                    <?php if (! empty($page)): ?>
                        <small><?= htmlentities($page->description); ?></small>
                    <?php endif; ?>
                </h1>
            </div>
            <div class="col-sm-2">
                <div class="dropdownCreate">
                    <button class="btn btn-default btn-sm">
                        <ul class="nav nav-pills">
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">Добавление контента</a>
                                <div class="dropdown-menu">
                                    <a class="dropdown-item" href="#">Action</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        </ul>
                    </button>
                </div>
            </div>
        </div>
    </div>
</header>

<div class="container">
    <div class="row">
        <ol class="breadcrumb">
            <?php if (isset($uri[2])): ?>
                <li class="breadcrumb-item"><a href="/admin">Dashboard</a></li>
                <li class="breadcrumb-item active">
                    <?php switch ($uri[2]):
                            case 'articles':
                                print 'Статьи';
                                break;
                            case 'cars':
                                print 'Авто';
                                break;
                            case 'reviews':
                                print 'Отзывы';
                                break;
                            case 'users':
                                print 'Пользователи';
                                break;
                            default: print '404';
                    endswitch; ?>
                </li>
            <?php else: ?>
                <li class="breadcrumb-item active">Dashboard</li>
            <?php endif; ?>
        </ol>
    </div>
</div>

</body>
</html>
