
<main>
    <div class="container">
        <div class="row">
            <div class="col-sm-3">
                <?php if (! empty($counts)): ?>
                    <div class="list-group">
                        <a href="/admin" class="list-group-item active">
                            <i class="fa fa-cog" aria-hidden="true"></i>
                            <span>Dashboard</span>
                        </a>
                        <a href="/admin/articles" class="list-group-item list-group-item-action">
                            <i class="fa fa-newspaper-o" aria-hidden="true"></i>
                            <span>Статьи</span>
                            <div class="badge"><?= htmlentities($counts['articles']); ?></div>
                        </a>
                        <a href="/admin/cars" class="list-group-item list-group-item-action">
                            <i class="fa fa-car" aria-hidden="true"></i>
                            <span>Авто</span>
                            <div class="badge"><?= htmlentities($counts['cars']); ?></div>
                        </a>
                        <a href="/admin/reviews" class="list-group-item list-group-item-action">
                            <i class="fa fa-pencil" aria-hidden="true"></i>
                            <span>Отзывы</span>
                            <div class="badge"><?= htmlentities($counts['reviews']); ?></div>
                        </a>
                        <a href="/admin/users" class="list-group-item list-group-item-action">
                            <i class="fa fa-user" aria-hidden="true"></i>
                            <span>Пользователи</span>
                            <div class="badge"><?= htmlentities($counts['users']); ?></div>
                        </a>
                    </div>
                <?php endif; ?>
            </div>