
<div class="col-sm-6">
    <?php if (\IhorRadchenko\App\Components\Session::has('errors')): ?>
        <div class="alert alert-danger error-block">
            <ul class="text-left">
                <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                    <?php foreach ($field as $error): ?>
                        <li><?= $error; ?></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
    <?php endif; ?>
    <?php if (! empty($car)): ?>
        <form action="/update/car" method="post" id="updateCar">
            <input type="hidden" name="MAX_FILE_SIZE" value="1000000">
            <div class="form-group">
                <?php if (! empty($brands)): ?>
                    <label for="brandId">Марка авто</label>
                    <select name="brand_id" id="brandId" required class="form-control">
                        <?php foreach ($brands as $brand): ?>
                            <option value="<?= $brand->getId(); ?>"
                                <?php if ($car->brand->getId() === $brand->getId()) {print 'selected';} ?>
                            ><?= htmlentities($brand->name); ?></option>
                        <?php endforeach; ?>
                    </select>
                <?php endif; ?>
            </div>
            <div class="form-group">
                <input type="text" name="model" class="form-control" placeholder="Модель" required value="<?= htmlentities($car->model); ?>">
            </div>
            <div class="form-group image-group">
                <div class="imagePreLoad">
                    <img src="<?= htmlentities($car->getIcon()); ?>" alt="" id="icon">
                </div>
                <label for="imageIconCar">Иконка автомобиля</label>
                <input type="file" class="form-control" id="imageIconCar">
                <small id="fileHelp" class="form-text">Желательно 166x92</small>
            </div>
            <div class="form-group image-group">
                <div class="imagePreLoad">
                    <img src="<?= htmlentities($car->getImage()); ?>" alt="" id="image">
                </div>
                <label for="imageHeadCar">Превью для модели</label>
                <input type="file" class="form-control" id="imageHeadCar">
                <small id="fileHelp" class="form-text">Желательно 1012x372</small>
            </div>
            <div class="form-group">
                <label for="editor">Описание для производителя</label>
                <textarea name="text" class="form-control" id="editor" rows="5" required>
                    <?= $car->text; ?>
                </textarea>
            </div>
            <input type="hidden" name="id" value="<?= $car->getId(); ?>">
            <input type="submit" class="form-control" name="update_car" value="Редактировать">
        </form>
    <?php endif; ?>
</div>

<script src="/vendor/ckeditor/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor', {
        customConfig: '/public/plugin/custom/ckeditor_config.js'
    })
</script>

</div>
</div>
</main>