
<div class="col-sm-6">
    <?php if (\IhorRadchenko\App\Components\Session::has('errors')): ?>
        <div class="alert alert-danger error-block">
            <ul class="text-left">
                <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                    <?php foreach ($field as $error): ?>
                        <li><?= $error; ?></li>
                    <?php endforeach; ?>
                <?php endforeach; ?>
            </ul>
        </div>
        <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
    <?php endif; ?>
    <?php if (! empty($mark)): ?>
        <form action="/update/mark" method="post" enctype="multipart/form-data" id="updateMark">
            <input type="hidden" name="MAX_FILE_SIZE" value="1000000">
            <div class="form-group">
                <input type="text" name="name" class="form-control" placeholder="Именование марки" required value="<?= htmlentities($mark->name); ?>">
            </div>
            <div class="form-group">
                <input type="text" name="description_page" class="form-control" placeholder="Лозунг компании" value="<?= htmlentities($mark->page->description); ?>">
            </div>
            <div class="form-group image-group">
                <div class="imagePreLoad">
                    <img src="<?= htmlentities($mark->getLogo()); ?>" alt="">
                </div>
                <label for="imageArticle">Логотип</label>
                <input type="file" class="form-control" name="logo" id="imageArticle">
                <small id="fileHelp" class="form-text">Желательно 100x75</small>
            </div>
            <div class="form-group">
                <label for="editor">Описание для производителя</label>
                <textarea name="description" class="form-control" id="editor" rows="5" required>
                    <?= $mark->description; ?>
                </textarea>
            </div>
            <input type="hidden" name="id" value="<?= $mark->getId(); ?>">
            <input type="submit" class="form-control" name="update_mark" value="Редактировать">
        </form>
    <?php endif; ?>
</div>

<script src="/vendor/ckeditor/ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace('editor', {
        customConfig: '/public/plugin/custom/ckeditor_config.js'
    })
</script>

</div>
</div>
</main>