
</div><!-- /.row -->
</div><!-- /.container -->

<footer class="blog-footer">
    <p>
        Copyright <?= date('Y'); ?>
    </p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
<script src="/public/js/calendar.js"></script>

<?php if (\IhorRadchenko\App\Components\Session::has('errors')): ?>
    <script>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'email')): ?>
            var email = <?= \IhorRadchenko\App\Components\Session::get('errors', 'email'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'password')): ?>
            var pass = <?= \IhorRadchenko\App\Components\Session::get('errors', 'password'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'passwordAgain')): ?>
            var pass_again = <?= \IhorRadchenko\App\Components\Session::get('errors', 'passwordAgain'); ?>;
        <?php endif; ?>
    </script>
    <script src="/public/js/signup.js"></script>
    <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
<?php endif; ?>
<?php if (\IhorRadchenko\App\Components\Session::has('login')): ?>
    <script>
        <?php if (\IhorRadchenko\App\Components\Session::get('login') === 'success'): ?>
            var loginSuccess = true;
        <?php else: ?>
            var loginSuccess = false;
        <?php endif; ?>
        <?php \IhorRadchenko\App\Components\Session::delete('login'); ?>
    </script>
    <script src="/public/js/login.js"></script>
<?php endif; ?>
</body>
</html>