
</div><!-- /.row -->
</div><!-- /.container -->

<footer class="blog-footer">
    <p>
        Copyright <?= date('Y'); ?>
    </p>
    <p>
        <a href="#">Back to top</a>
    </p>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
<script src="/public/js/calendar.js"></script>
<script src="/public/js/review-form.js"></script>

<?php if (\IhorRadchenko\App\Components\Session::get('signup') === 'fail'): ?>
    <script>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'email')): ?>
            var email = <?= \IhorRadchenko\App\Components\Session::get('errors', 'email'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'password')): ?>
            var pass = <?= \IhorRadchenko\App\Components\Session::get('errors', 'password'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'passwordAgain')): ?>
            var pass_again = <?= \IhorRadchenko\App\Components\Session::get('errors', 'passwordAgain'); ?>;
        <?php endif; ?>
    </script>
    <script src="/public/js/signup.js"></script>
    <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
    <?php \IhorRadchenko\App\Components\Session::delete('signup'); ?>
<?php endif; ?>

<?php if (\IhorRadchenko\App\Components\Session::has('login')): ?>
    <script>
        <?php if (\IhorRadchenko\App\Components\Session::get('login') === 'success'): ?>
            var loginSuccess = true;
        <?php else: ?>
            var loginSuccess = false;
        <?php endif; ?>
        <?php \IhorRadchenko\App\Components\Session::delete('login'); ?>
    </script>
    <script src="/public/js/login.js"></script>
<?php endif; ?>

<?php if (\IhorRadchenko\App\Components\Session::get('update_user') === 'fail'): ?>
    <script>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'email')): ?>
            var email = <?= \IhorRadchenko\App\Components\Session::get('errors', 'email'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'f_name')): ?>
            var f_name = <?= \IhorRadchenko\App\Components\Session::get('errors', 'f_name'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'l_name')): ?>
            var l_name = <?= \IhorRadchenko\App\Components\Session::get('errors', 'l_name'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'phone_number')): ?>
            var phone_number = <?= \IhorRadchenko\App\Components\Session::get('errors', 'phone_number'); ?>;
        <?php endif; ?>
    </script>
    <script src="/public/js/update_user.js"></script>
    <?php \IhorRadchenko\App\Components\Session::delete('update_user'); ?>
    <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
<?php endif; ?>

<?php if (\IhorRadchenko\App\Components\Session::get('change_pass') === 'fail'): ?>
    <script>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'old_pass')): ?>
            var old_pass = <?= \IhorRadchenko\App\Components\Session::get('errors', 'old_pass'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'password')): ?>
            var pass = <?= \IhorRadchenko\App\Components\Session::get('errors', 'password'); ?>;
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors', 'passwordAgain')): ?>
            var pass_again = <?= \IhorRadchenko\App\Components\Session::get('errors', 'passwordAgain'); ?>;
        <?php endif; ?>
    </script>
    <script src="/public/js/change_pass.js"></script>
    <?php \IhorRadchenko\App\Components\Session::delete('change_pass'); ?>
    <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
<?php endif; ?>

</body>
</html>