
</div><!-- /.row -->
</div><!-- /.container -->

<footer class="blog-footer">
    <p>
        Copyright <?= date('Y'); ?>
    </p>
</footer>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS -->
<script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/jquery.validate.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.17.0/additional-methods.min.js"></script>
<script src="/public/js/messages_ru.min.js"></script>
<script src="/public/js/validate.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js"></script>
<script src="/public/js/calendar.js"></script>
<script src="/public/js/review-page.js"></script>
<script src="/public/js/forum.js"></script>
<script src="/public/js/car.js"></script>
<script src="/public/js/go_top.js"></script>

<?php if (\IhorRadchenko\App\Components\Session::has('login_success') ||
            \IhorRadchenko\App\Components\Session::has('login_fail')): ?>
    <script>
        $("#btn-login").click();
    </script>
    <?php \IhorRadchenko\App\Components\Session::delete('login_success'); ?>
    <?php \IhorRadchenko\App\Components\Session::delete('login_fail'); ?>
<?php endif; ?>

<?php if (\IhorRadchenko\App\Components\Session::has('signup_error') &&
\IhorRadchenko\App\Components\Session::get('signup_error') === 'fail'): ?>
    <script>
        $("#btn-signup").click();
    </script>
    <?php \IhorRadchenko\App\Components\Session::delete('signup_error'); ?>
    <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
<?php endif; ?>

<?php if (\IhorRadchenko\App\Components\Session::has('add_review') &&
            \IhorRadchenko\App\Components\Session::get('add_review')): ?>
    <script>
        $("#btn-addReview").click();
    </script>
    <?php \IhorRadchenko\App\Components\Session::delete('add_review'); ?>
<?php endif; ?>

</body>
</html>