
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="/public/css/main.css">
    <link rel="stylesheet" href="/public/css/calendar.css">
    <link rel="stylesheet" href="/public/css/style.css">
</head>
<body>

<div class="blog-masthead">
    <div class="container">
        <nav class="nav">
            <?php foreach ($categories as $category): ?>
                <a class="nav-link <?php if (explode('/', $_SERVER['REQUEST_URI'])[1] === $category->link):
                    print 'active';
                endif; ?>"
                   href="/<?= htmlentities($category->link); ?>"><?= htmlentities($category->name); ?></a>
            <?php endforeach; ?>
        </nav>
    </div>
</div>

<div class="blog-header">
    <div class="container">
        <h1 class="blog-title">The Bootstrap Blog</h1>
        <p class="lead blog-description">An example blog template built with Bootstrap.</p>
    </div>
</div>

<div class="container">
    <div class="row">