
<!DOCTYPE html>
<html lang="ru">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?= htmlentities($page->title); ?></title>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css" integrity="sha384-/Y6pD6FV/Vv2HJnA6t+vslU6fwYXjCFtcEpHbNJ0lyAFsXTsjBbfaDjzALeQsN6M" crossorigin="anonymous">
    <link rel="stylesheet" href="/public/css/main.css">
    <link rel="stylesheet" href="/public/css/calendar.css">
    <link rel="stylesheet" href="/public/css/style.css">
</head>
<body>

<div class="blog-masthead">
    <div class="container">
        <nav class="nav">
            <a href="/" class="nav-link <?php if (explode('/', $_SERVER['REQUEST_URI'])[1] === ''):
                print 'active';
            endif; ?>">Главная</a>
            <?php if (! empty($categories)): ?>
                <?php foreach ($categories as $category): ?>
                    <a class="nav-link <?php if (explode('/', $_SERVER['REQUEST_URI'])[1] === $category->link):
                        print 'active';
                    endif; ?>"
                       href="/<?= htmlentities($category->link); ?>"><?= htmlentities($category->name); ?></a>
            <?php endforeach; ?>
            <?php endif; ?>
        </nav>
    </div>
</div>

<div class="blog-header">
    <div class="container">
        <div class="row">
            <div class="col-sm-8">
                <h1 class="blog-title"><?= htmlentities($page->title); ?></h1>
                <p class="lead blog-description"><?= htmlentities(mb_ucfirst(mb_strtolower($page->description))); ?></p>
            </div>
            <div class="col-sm-4">
                <div class="signup-login">
                    <button class="user-action" data-toggle="modal" data-target="#login">ВХОД</button>
                    <span style="color: #999">|</span>
                    <button class="user-action" data-toggle="modal" data-target="#signup">РЕГИСТРАЦИЯ</button>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="login" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-signin">
                <div class="modal-header">
                    <h2 class="form-signin-heading">Вход на сайт</h2>
                    <button class="close" type="button" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <label for="inputEmail" class="sr-only">Емейл адресс</label>
                    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus autocomplete="on">
                    <label for="inputPassword" class="sr-only">Пароль</label>
                    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required autocomplete="off">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" value="remember-me"> Запомнить меня
                        </label>
                    </div>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-primary btn-block" type="submit" value="Войти">
                    <button class="btn btn-danger" type="button" data-dismiss="modal">Отмена</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="modal fade" id="signup" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-signup">
                <div class="modal-header">
                    <h2 class="form-signup-heading">Регистрация</h2>
                    <button class="close" type="button" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <label for="inputEmail" class="sr-only">Емейл адресс</label>
                    <input type="email" name="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus autocomplete="on">
                    <label for="inputPassword" class="sr-only">Пароль</label>
                    <input type="password" name="password" id="inputPassword" class="form-control" placeholder="Password" required autocomplete="off">
                    <label for="repeatPassword" class="sr-only">Повторите пароль</label>
                    <input type="password" name="password_again" id="repeatPassword" class="form-control" placeholder="Please repeat your password" required autocomplete="off">
                    <label for="inputName" class="sr-only">Имя</label>
                    <input type="text" name="f_name" id="inputName" class="form-control" placeholder="Name" required autocomplete="on">
                    <label for="inputSurname" class="sr-only">Фамилия</label>
                    <input type="text" name="l_name" id="inputSurname" class="form-control" placeholder="Surname" required autocomplete="on">
                </div>
                <div class="modal-footer">
                    <input class="btn btn-primary btn-block" type="submit" value="Зарегистрироваться">
                    <button class="btn btn-danger" type="button" data-dismiss="modal">Отмена</button>
                </div>
            </form>
        </div>
    </div>
</div>

<div class="container">
    <div class="row">