
<div class="col-sm-3 offset-sm-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
        <h4>Календарь</h4>
        <table id="calendar2">
            <thead>
            <tr><td>‹<td colspan="5"><td>›
            <tr><td>Пн<td>Вт<td>Ср<td>Чт<td>Пт<td>Сб<td>Вс
            <tbody>
        </table>
    </div>
    <div class="sidebar-module">
        <h4>Производители</h4>
        <ol class="list-unstyled">
            <?php foreach ($brands as $brand): ?>
                <li class="sidebarItem <?php if (isset(explode('/', $_SERVER['REQUEST_URI'])[2])
                    && explode('/', $_SERVER['REQUEST_URI'])[2] === str_replace(' ', '-', mb_strtolower($brand->name))):
                                                print 'active-SideBar';
                                             endif;?>">
                    <a href="/mark/<?= htmlentities(str_replace(' ', '-', mb_strtolower($brand->name))); ?>" class="sidebarLink">
                        <div class="sidebarPic">
                            <img src="<?= htmlentities($brand->getLogo()); ?>" alt="">
                        </div>
                        <div class="sidebarText">
                            <span><?= htmlentities(mb_strtoupper($brand->name)); ?></span>
                        </div>
                    </a>
                </li>
            <?php endforeach; ?>
        </ol>
    </div>

</div><!-- /.blog-sidebar -->