
<div class="col-sm-3 offset-sm-1 blog-sidebar">
    <div class="sidebar-module sidebar-module-inset">
        <h4>Календарь</h4>
        <table id="calendar2">
            <thead>
            <tr><td>‹<td colspan="5"><td>›
            <tr><td>Пн<td>Вт<td>Ср<td>Чт<td>Пт<td>Сб<td>Вс
            <tbody>
        </table>
    </div>
    <div class="sidebar-module">
        <h4>Archives</h4>
        <ol class="list-unstyled">
            <?php foreach ($brands as $brand): ?>
                <li><?= $brand->name; ?></li>
            <?php endforeach; ?>
        </ol>
    </div>

</div><!-- /.blog-sidebar -->