
<div class="col-sm-3">
    <h2 class="blog-header">Активные темы</h2>
    <?php if (! empty($forums)): ?>
        <?php foreach ($forums as $theme): ?>
            <div class="theme">
                <a href=""><?= htmlentities(mb_strtoupper($theme->title)); ?></a>
                <div class="dopInfo">
                    <div>Ответов</div>
                    <a href="/<?= htmlentities($theme->parent->getAlias()); ?>"><?= htmlentities(mb_ucfirst(mb_strtolower($theme->parent->title))); ?></a>
                </div>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>