
<div class="col-sm-3"></div>

<div class="col-sm-5">
    <div class="blog-post">
        <?php if (! empty($forums)): ?>
            <?php foreach ($forums as $section): ?>
                <a href="<?= $section->getAlias(); ?>" class="forumSection">
                    <span class="forum-title"><?= $section->title; ?></span>
                    <span class="count-right text-center">
                        <?= $section->count; ?>
                    </span>
                </a>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>