
<div class="col-sm-5">
    <div class="blog-post">
        <?php if (! empty($forums)): ?>
            <?php foreach ($forums as $section): ?>
                <a href="<?= htmlentities($section->getAlias()); ?>" class="forumSection">
                    <span class="forum-title"><?= htmlentities(mb_strtoupper($section->title)); ?></span>
                    <span class="count-right text-center">
                        <?= htmlentities($section->count); ?>
                    </span>
                </a>
            <?php endforeach; ?>
        <?php endif; ?>
    </div>
</div>