
<?php if (! empty($totalComments)): ?>
    <script>
        var totalComments = <?= $totalComments; ?>;
    </script>
<?php endif; ?>

<?php if (! empty($theme)): ?>
    <script>
        var themeId = <?= $theme->getId(); ?>;
    </script>
<?php endif; ?>

<div class="col-sm-5">
    <?php if (! empty($theme)): ?>
        <h1 class="blog-header forum-header"><?= htmlentities(mb_strtoupper($theme->title)); ?></h1>
    <?php endif; ?>
        <div class="comments">
            <?php if (! empty($forums)): ?>
                <?php foreach ($forums as $comment): ?>
                    <div class="comment" data-idComment="<?= $comment->getId(); ?>">
                        <div class="authorComment">
                            <div class="authorAvatar">
                                <img src="/public/img/avatar/defaultAvatar.png" alt="">
                            </div>
                            <div class="authorName text-center">
                                <?= htmlentities($comment->author->getFullName()); ?>
                            </div>
                            <div class="commentDate text-center">
                                <?= htmlentities($comment->getDate()); ?>
                            </div>
                        </div>
                        <?php if (\IhorRadchenko\App\Models\User::isAdmin() || (\IhorRadchenko\App\Components\Session::has('user') && \IhorRadchenko\App\Components\Session::get('user')->getId() === $comment->author->getId())): ?>
                            <div class="control">
                                <button class="btn-update" data-id="<?= $comment->getId(); ?>">
                                    <i class="fa fa-pencil-square-o" aria-hidden="true"></i>
                                </button>
                                <button class="btn-delete" data-id="<?= $comment->getId(); ?>">
                                    <i class="fa fa-times" aria-hidden="true"></i>
                                </button>
                            </div>
                        <?php endif; ?>
                        <div class="commentText">
                            <?php if (isset($bbCode)): ?>
                                <?= $bbCode->bbCode(nl2br(htmlentities($comment->text))); ?>
                            <?php endif; ?>
                        </div>
                    </div>
                <?php endforeach; ?>
            <?php else: ?>
                <div>В данной теме еще нет сообщений</div>
            <?php endif; ?>
        </div>

    <?php if (! empty($forums) && isset($totalComments) && $totalComments > 1): ?>
        <button class="btn btn-block btn-success" id="moreComments">ПОКАЗАТЬ БОЛЬШЕ СООБЩЕНИЙ</button>
    <?php endif; ?>

    <?php if (\IhorRadchenko\App\Components\Session::has('user')): ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors')): ?>
            <div class="alert alert-danger">
                <ul>
                    <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                        <?php foreach ($field as $error): ?>
                        <li><?= $error; ?></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
        <?php endif; ?>
        <?php if (\IhorRadchenko\App\Models\User::isVerified()): ?>
            <h2 class="blog-header forum-header">Добавить сообщение</h2>
            <?php if (! \IhorRadchenko\App\Components\Session::get('user')->f_name): ?>
                <div class="form-group">
                    <input type="text" class="form-control" required minlength="2" maxlength="30" placeholder="Имя" name="f_name">
                </div>
            <?php endif; ?>
            <textarea name="text" id="commentId" cols="44" rows="5" placeholder="Сообщение" required></textarea>
            <button type="submit" class="btn btn-block btn-success btn-sm" id="addComment">ОТПРАВИТЬ</button>
        <?php endif; ?>
    <?php endif; ?>

</div>

<div id="forModal"></div>