
<?php if (! empty($totalComments) && ! empty($theme)): ?>
    <script>
        var totalComments = <?= $totalComments; ?>;
        var themeId = <?= $theme->getId(); ?>;
    </script>
<?php endif; ?>

<div class="col-sm-5">
    <?php if (! empty($theme)): ?>
        <h1 class="blog-header forum-header"><?= htmlentities(mb_strtoupper($theme->title)); ?></h1>
    <?php endif; ?>
    <?php if (! empty($forums)): ?>
        <div class="comments">
            <?php foreach ($forums as $comment): ?>
                <div class="comment">
                    <div class="authorComment">
                        <div class="authorAvatar">
                            <img src="/public/img/avatar/defaultAvatar.png" alt="">
                        </div>
                        <div class="authorName text-center">
                            <?= htmlentities($comment->author->getFullName()); ?>
                        </div>
                        <div class="commentDate text-center">
                            <?= htmlentities($comment->getDate()); ?>
                        </div>
                    </div>
                    <div class="commentText">
                        <?= nl2br(htmlentities($comment->text)); ?>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    <?php else: ?>
        <div>В данной теме еще нет сообщений</div>
    <?php endif; ?>

    <?php if (! empty($forums) && isset($totalComments) && $totalComments > 1): ?>
        <button class="btn btn-block btn-success" id="moreComments">ПОКАЗАТЬ БОЛЬШЕ СООБЩЕНИЙ</button>
    <?php endif; ?>

    <?php if (\IhorRadchenko\App\Components\Session::has('user')): ?>
        <?php if (\IhorRadchenko\App\Components\Session::has('errors')): ?>
            <div class="alert alert-danger">
                <ul>
                    <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                        <?php foreach ($field as $error): ?>
                        <li><?= $error; ?></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
        <?php endif; ?>
    <h2 class="blog-header forum-header">Добавить сообщение</h2>
        <textarea name="text" id="commentId" cols="44" rows="5" placeholder="Сообщение" required></textarea>
        <button type="submit" class="btn btn-block btn-success btn-sm" id="addComment">ОТПРАВИТЬ</button>
    <?php endif; ?>

</div>