
<?php if (! empty($data)): ?>
    <?php foreach ($data as $article): ?>
        <a href="/<?= htmlentities($article->category->link) . '/' . htmlentities($article->alias); ?>" class="article">
                    <span class="articleImg">
                        <img src="<?= htmlentities($article->getImage()); ?>" alt="" class="articlePic">
                    </span>
            <div class="article-description">
                        <span class="article-title">
                            <?= htmlentities($article->title); ?>
                        </span>
                <span class="article-short-text">
                            <?= htmlentities($article->description); ?>
                        </span>
                <span class="article-date">
                            <?= htmlentities($article->getDate()); ?>
                        </span>
            </div>
        </a>
    <?php endforeach; ?>
<?php endif; ?>
