
<!-- Modal -->
<?php if (! empty($data)): ?>
    <div class="modal fade" id="updateComments" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title">Обновление комментария</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <textarea name="text" id="textComment" cols="30" rows="10" required placeholder="Текст сообщения" class="form-control"><?= trim(nl2br(htmlentities($data->text))); ?></textarea>
                    </div>
                    <input type="hidden" id="updateCommentId" value="<?= $data->getId(); ?>">
                    <div class="modal-footer">
                        <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                        <button type="submit" class="btn btn-primary btnUpdateComment">Обновить</button>
                    </div>
            </div>
        </div>
    </div>
<?php endif; ?>