

<!-- Modal -->
<?php if (! empty($data)): ?>
    <div class="modal fade" id="modalCars" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Редактировать</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="container">
                        <div class="row">
                            <div class="col-sm-6">
                                <form action="/admin/mark/update" method="post">
                                    <input type="hidden" name="mark" value="<?= $data->brand->getId(); ?>">
                                    <input type="submit" name="update_mark" value="Марку" class="form-control btn-primary">
                                </form>
                            </div>
                            <div class="col-sm-6">
                                <form action="/admin/cars/update" method="post">
                                    <input type="hidden" name="model" value="<?= $data->getId(); ?>">
                                    <input type="submit" name="update_model" value="Модель" class="form-control btn-primary">
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>