
<div class="col-sm-9">
    <form class="text-center" method="post" id="changePassForm" action="/user/change_password">
        <?php if (\IhorRadchenko\App\Components\Session::has('change_pass') &&
            \IhorRadchenko\App\Components\Session::get('change_pass') === 'fail'): ?>
            <div class="alert alert-danger error-block">
                <ul class="text-left">
                    <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                        <?php foreach ($field as $error): ?>
                            <li><?= $error; ?></li>
                        <?php endforeach; ?>
                    <?php endforeach; ?>
                </ul>
            </div>
            <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
            <?php \IhorRadchenko\App\Components\Session::delete('change_pass'); ?>
        <?php endif; ?>
        <div class="form-group">
            <input type="password" class="form-control" name="oldPassword" placeholder="Старый пароль" required>
        </div>
        <div class="form-group">
            <input type="password" class="form-control" id="inputPassword-ChangePassword" name="password" placeholder="Новый пароль" required>
        </div>
        <div class="form-group">
            <input type="password" class="form-control" name="passwordAgain" placeholder="Подтвердите пароль" required>
        </div>
        <input type="hidden" name="change_password_token" value="<?= \IhorRadchenko\App\Components\Token::generate('change_password_token'); ?>">
        <input type="submit" class="btn btn-primary" value="ПОДТВЕРДИТЬ" name="change_password">
    </form>
</div>