
<div class="col-sm-9">
    <form class="text-center" method="post" action="/user/change_password">
        <div class="form-group">
            <div class="alert alert-danger error-block" id="errorOldPassword">
                <ul id="errorOldPasswordList" class="text-left">
                </ul>
            </div>
            <input type="password" class="form-control" id="inputOldPassword" name="oldPassword" placeholder="Старый пароль" required>
        </div>
        <div class="form-group">
            <div class="alert alert-danger error-block" id="errorPassword-ChangePassword">
                <ul id="errorPassword-ChangePasswordList" class="text-left">
                </ul>
            </div>
            <input type="password" class="form-control" id="inputPassword-ChangePassword" name="password" placeholder="Новый пароль" required>
        </div>
        <div class="form-group">
            <div class="alert alert-danger error-block" id="errorPasswordAgain-ChangePassword">
                <ul id="errorPasswordAgain-ChangePasswordList" class="text-left">
                </ul>
            </div>
            <input type="password" class="form-control" name="passwordAgain" id="inputPasswordAgain-ChangePassword" placeholder="Подтвердите пароль" required>
        </div>
        <input type="hidden" name="change_password_token" value="<?= \IhorRadchenko\App\Components\Token::generate('change_password_token'); ?>">
        <input type="submit" class="btn btn-primary" value="ПОДТВЕРДИТЬ" name="change_password">
    </form>
</div>