
<div class="col-sm-9">
    <div class="myInfo">
        <?php if (! empty($user)): ?>
            <div class="infoTitle">
                Ваше имя:
            </div>
            <div class="infoValue">
                <?php if (! empty(trim($user->getFullName()))): ?>
                    <?= trim($user->getFullName()); ?>
                <?php else: ?>
                    <a href="/user/profile"><u>Не указано</u></a>
                <?php endif; ?>
            </div>
            <div class="infoTitle">
                Электронная почта:
            </div>
            <div class="infoValue">
                <?= $user->email; ?>
            </div>
            <div class="infoTitle">
                Телефон:
            </div>
            <div class="infoValue">
                <?php if (! empty($user->phone_number)): ?>
                    <?= $user->phone_number; ?>
                <?php else: ?>
                    <a href="/user/profile"><u>Не указано</u></a>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</div>

