
<div class="col-sm-9">
    <div class="myInfo">
        <?php if (! empty($user)): ?>
            <div class="infoTitle">
                Ваше имя:
            </div>
            <div class="infoValue">
                <?= htmlentities($user->getFullName()) ?: '<a href="/user/profile"><u>Не указано</u></a>'; ?>
            </div>
            <div class="infoTitle">
                Электронная почта:
            </div>
            <div class="infoValue">
                <?= htmlentities($user->email); ?>
            </div>
            <div class="infoTitle">
                Город:
            </div>
            <div class="infoValue">
                <?= htmlentities($user->city) ?: '<a href="/user/profile"><u>Не указано</u></a>'; ?>
            </div>
            <div class="infoTitle">
                Телефон:
            </div>
            <div class="infoValue">
                <?= htmlentities($user->phone_number) ?: '<a href="/user/profile"><u>Не указано</u></a>'; ?>
            </div>
        <?php endif; ?>
    </div>
</div>

