
<div class="col-sm-9">
    <div class="myInfo">
        <?php if (! empty($user)): ?>
            <div class="infoTitle">
                Ваше имя:
            </div>
            <div class="infoValue">
                <?php if (! empty($user->getFullName())): ?>
                    <?= htmlentities($user->getFullName()); ?>
                <?php else: ?>
                    <a href="/user/profile"><u>Не указано</u></a>
                <?php endif; ?>
            </div>
            <div class="infoTitle">
                Электронная почта:
            </div>
            <div class="infoValue">
                <?= htmlentities($user->email); ?>
            </div>
            <div class="infoTitle">
                Город:
            </div>
            <div class="infoValue">
                <?php if (! empty($user->city)): ?>
                    <?= htmlentities($user->city); ?>
                <?php else: ?>
                    <a href="/user/profile"><u>Не указано</u></a>
                <?php endif; ?>
            </div>
            <div class="infoTitle">
                Телефон:
            </div>
            <div class="infoValue">
                <?php if (! empty($user->phone_number)): ?>
                    <?= htmlentities($user->phone_number); ?>
                <?php else: ?>
                    <a href="/user/profile"><u>Не указано</u></a>
                <?php endif; ?>
            </div>
        <?php endif; ?>
    </div>
</div>

