
<div class="col-sm-9">
    <form class="text-center">
        <?php if (! empty($user)): ?>
            <div class="form-group">
                <input type="text" class="form-control" id="inputName" name="f_name" placeholder="Имя" value="<?= $user->f_name; ?>">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" id="inputSurname" name="l_name" placeholder="Фамилия" value="<?= $user->l_name; ?>">
            </div>
            <div class="form-group">
                <input type="email" class="form-control" name="email" value="<?= $user->email; ?>" id="inputEmail" aria-describedby="emailHelp" placeholder="E-Mail" required>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="phone_number" value="<?= $user->phone_number; ?>" id="inputPhone" placeholder="Телефон (например: +380999999999)">
            </div>
            <button type="submit" class="btn btn-primary">ПОДТВЕРДИТЬ</button>
        <?php endif; ?>
    </form>
</div>