
<div class="col-sm-9">
    <form class="text-center" method="post" id="profileForm" action="/user/profile">
        <?php if (! empty($user)): ?>
            <?php if (\IhorRadchenko\App\Components\Session::has('update_user') &&
                \IhorRadchenko\App\Components\Session::get('update_user') === 'fail'): ?>
                <div class="alert alert-danger error-block">
                    <ul class="text-left">
                        <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                            <?php foreach ($field as $error): ?>
                                <li><?= $error; ?></li>
                            <?php endforeach; ?>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
                <?php \IhorRadchenko\App\Components\Session::delete('update_user'); ?>
            <?php endif; ?>
            <div class="form-group">
                <input type="text" class="form-control" id="inputName" name="f_name" placeholder="Имя" value="<?= htmlentities($user->f_name); ?>" required>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" id="inputSurname" name="l_name" placeholder="Фамилия" value="<?= htmlentities($user->l_name); ?>" required>
            </div>
            <div class="form-group">
                <input type="email" class="form-control" name="email" value="<?= htmlentities($user->email); ?>" id="inputEmail" aria-describedby="emailHelp" placeholder="E-Mail" required>
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="city" value="<?= htmlentities($user->city); ?>" id="inputCity" placeholder="Город">
            </div>
            <div class="form-group">
                <input type="text" class="form-control" name="phone_number" value="<?= htmlentities($user->phone_number); ?>" id="inputPhone" placeholder="Телефон (например: +380999999999)">
            </div>
            <input type="hidden" name="update_user_token" value="<?= \IhorRadchenko\App\Components\Token::generate('update_user_token'); ?>">
            <input type="submit" class="btn btn-primary" value="ПОДТВЕРДИТЬ" name="update_user">
        <?php endif; ?>
    </form>
</div>