
<div class="col-sm-9">
    <form class="text-center" method="post" action="/user/profile">
        <?php if (! empty($user)): ?>
            <div class="form-group">
                <div class="alert alert-danger error-block" id="errorFName">
                    <ul id="errorFNameList" class="text-left">
                    </ul>
                </div>
                <input type="text" class="form-control" id="inputName" name="f_name" placeholder="Имя" value="<?= $user->f_name; ?>" required>
            </div>
            <div class="form-group">
                <div class="alert alert-danger error-block" id="errorLName">
                    <ul id="errorLNameList" class="text-left">
                    </ul>
                </div>
                <input type="text" class="form-control" id="inputSurname" name="l_name" placeholder="Фамилия" value="<?= $user->l_name; ?>" required>
            </div>
            <div class="form-group">
                <div class="alert alert-danger error-block" id="errorEmailUpUser">
                    <ul id="errorEmailUpUserList" class="text-left">
                    </ul>
                </div>
                <input type="email" class="form-control" name="email" value="<?= $user->email; ?>" id="inputEmail" aria-describedby="emailHelp" placeholder="E-Mail" required>
            </div>
            <div class="form-group">
                <div class="alert alert-danger error-block" id="errorPhoneNumber">
                    <ul id="errorPhoneNumberList" class="text-left">
                    </ul>
                </div>
                <input type="text" class="form-control" name="phone_number" value="<?= $user->phone_number; ?>" id="inputPhone" placeholder="Телефон (например: +380999999999)" required>
            </div>
            <input type="hidden" name="update_user_token" value="<?= \IhorRadchenko\App\Components\Token::generate('update_user_token'); ?>">
            <input type="submit" class="btn btn-primary" value="ПОДТВЕРДИТЬ" name="update_user">
        <?php endif; ?>
    </form>
</div>