
<div class="col-sm-3">
    <ul class="nav flex-column">
        <li class="nav-item personal-area-btn personal-area-btn-active">
            <a class="nav-link" href="/user">Личный кабинет</a>
        </li>
        <li class="nav-item personal-area-btn">
            <a class="nav-link" href="/user/profile">Мои данные</a>
        </li>
        <li class="nav-item personal-area-btn">
            <a class="nav-link" href="/user/change_password">Изменить пароль</a>
        </li>
        <li class="nav-item personal-area-btn">
            <a class="nav-link" href="/logout">Выход</a>
        </li>
    </ul>
</div>