
<?php if (! empty($data)): ?>
    <?php foreach ($data as $category): ?>
        <tr class="table-row">
            <td class="firstLetterUC">
                <a href="/<?= htmlentities($category->link); ?>">
                    <?= htmlentities(mb_strtolower($category->name)); ?>
                </a>
            </td>
            <td>
                <?= htmlentities($category->countNews); ?>
            </td>
            <td>
                <button data-id="<?= $category->getId(); ?>" class="btn btn-primary btn-sm btn-update">
                    Редактировать
                </button>
            </td>
            <td>
                <button data-id="<?= $category->getId(); ?>" class="btn btn-danger btn-sm btn-delete">Удалить</button>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
