
<?php if (! empty($data)): ?>
    <?php foreach ($data as $review): ?>
        <tr>
            <td>
                <a href="/mark/<?= htmlentities(str_replace(' ', '-', mb_strtolower($review->car->brand->name))) . '/' . htmlentities(str_replace(' ', '-', mb_strtolower($review->car->model))); ?>">
                    <?= htmlentities(mb_strtoupper($review->car->brand->name)) . ' ' . htmlentities(mb_strtoupper($review->car->model)); ?>
                </a>
            </td>
            <td>
                <?= htmlentities($review->author->email); ?>
            </td>
            <td><?= htmlentities($review->rating) . '/5'; ?></td>
            <td>
                <?= $review->formatDate(); ?>
            </td>
            <td>
                <button class="showMore" data-id="<?= $review->getId(); ?>">
                    <i class="fa fa-eye" aria-hidden="true"></i>
                </button>
            </td>
            <td>
                <button class="btn btn-danger btn-sm btn-delete" data-id="<?= $data->getId(); ?>">Удалить</button>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>
