
<?php if (! empty($data)): ?>
    <?php foreach ($data as $user): ?>
        <tr>
            <td><?= htmlentities(mb_ucwords($user->getFullName())); ?></td>
            <td><?= htmlentities($user->email); ?></td>
            <td><?= $user->formatDate(); ?></td>
            <td>
                <button class="btn btn-primary btn-sm btn-update" data-id="<?= $user->getId(); ?>">Редактировать</button>
            </td>
            <td>
                <button class="btn btn-danger btn-sm btn-delete" data-id="<?= $user->getId(); ?>">Удалить</button>
            </td>
        </tr>
    <?php endforeach; ?>
<?php endif; ?>