
<!-- Modal -->
<?php if (! empty($data)): ?>
    <div class="modal fade" id="reviewModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title">Пользователь</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <div class="userInfo">
                        Email: <?= htmlentities($data->email) ?: 'Не указано'; ?>
                    </div>
                    <div class="userInfo">
                        Имя: <?= htmlentities($data->f_name) ?: 'Не указано'; ?>
                    </div>
                    <div class="userInfo">
                        Фамилия: <?= htmlentities($data->l_name) ?: 'Не указано'; ?>
                    </div>
                    <div class="userInfo">
                        Номер телефона: <?= htmlentities($data->phone_number) ?: 'Не указано'; ?>
                    </div>
                    <div class="userInfo">
                        Город: <?= htmlentities($data->city) ?: 'Не указано'; ?>
                    </div>
                    <div class="userInfo">
                        Роль: <?= htmlentities($data->group) ?: 'Не указано'; ?>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Отмена</button>
                </div>
            </div>
        </div>
    </div>
<?php endif; ?>