
<div class="col-sm-9">
    <?php if (! empty($news)): ?>
        <div class="panel">
            <div class="panel-header main-color-bg">
                <h2>Статьи</h2>
            </div>
            <div class="panel-body">
                <form method="post">
                    <?php if (! empty($categories)): ?>
                        <select name="category" id="selectCategory" class="form-control">
                            <option value="all"></option>
                            <?php foreach ($categories as $category): ?>
                                <option value="<?= htmlentities($category->link); ?>"><?= htmlentities($category->name); ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>
                </form>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Заголовок</th>
                        <th>Категория</th>
                        <th>Дата публикации</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody>
                    <?php foreach ($news as $article): ?>
                        <tr>
                            <td class="firstLetterUC">
                                <a href="/<?= htmlentities($article->category->link) . '/' . htmlentities($article->alias); ?>">
                                    <?= htmlentities(mb_strtolower($article->title)); ?>
                                </a>
                            </td>
                            <td>
                                <a href="/<?= htmlentities($article->category->link); ?>">
                                    <?= htmlentities($article->category->name); ?>
                                </a>
                            </td>
                            <td><?= $article->formatDate(); ?></td>
                            <td>
                                <a href="" class="btn btn-primary btn-sm">Редактировать</a>
                            </td>
                            <td>
                                <a href="" class="btn btn-danger btn-sm">Удалить</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <?php if (isset($totalPages) && $totalPages > 1): ?>
                    <button class="btn btn-block btn-success" id="moreArticle">ЕЩЕ СТАТЬИ</button>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<?php if (isset($totalPages)): ?>
    <script>
        var totalPages = <?= $totalPages; ?>;
    </script>
<?php endif; ?>

</div>
</div>
</main>