<?php $uri = explode('/', $_SERVER['REQUEST_URI']); ?>
<div class="col-sm-9">
    <?php if (! empty($news)): ?>
        <div class="panel">
            <div class="panel-header main-color-bg">
                <h2>Статьи</h2>
            </div>
            <div class="panel-body">
                <form method="post" id="categoryForm">
                    <?php if (! empty($categories)): ?>
                        <select name="category" id="selectCategory" class="form-control">
                            <option value="all"
                            <?php if (! isset($uri[3])) {print 'selected';} ?>
                            ></option>
                            <?php foreach ($categories as $category): ?>
                                <option value="<?= htmlentities($category->link); ?>"
                                    <?php if (isset($uri[3]) && $uri[3] === htmlentities($category->link)) {print 'selected';} ?>
                                ><?= htmlentities($category->name); ?></option>
                            <?php endforeach; ?>
                        </select>
                    <?php endif; ?>
                </form>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Заголовок</th>
                        <th>Категория</th>
                        <th>Дата публикации</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody class="table-body">
                    <?php foreach ($news as $article): ?>
                        <tr class="table-row">
                            <td class="firstLetterUC">
                                <a href="/<?= htmlentities($article->category->link) . '/' . htmlentities($article->alias); ?>">
                                    <?= htmlentities(mb_strtolower($article->title)); ?>
                                </a>
                            </td>
                            <td>
                                <a href="/<?= htmlentities($article->category->link); ?>">
                                    <?= htmlentities($article->category->name); ?>
                                </a>
                            </td>
                            <td><?= $article->formatDate(); ?></td>
                            <td>
                                <form action="/admin/articles/update" method="post">
                                    <input type="hidden" value="<?= $article->getId(); ?>" name="article_id">
                                    <input type="submit" class="btn btn-primary btn-sm" value="Редактировать" name="update_article">
                                </form>
                            </td>
                            <td>
                                <button data-id="<?= $article->getId(); ?>" class="btn btn-danger btn-sm btn-delete">Удалить</button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <?php if (isset($totalPages) && $totalPages > 1): ?>
                    <button class="btn btn-block btn-success" id="moreArticle">ЕЩЕ СТАТЬИ</button>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<?php if (isset($totalPages)): ?>
    <script>
        var totalPages = <?= $totalPages; ?>;
    </script>
<?php endif; ?>

</div>
</div>
</main>