<?php $uri = explode('/', $_SERVER['REQUEST_URI']); ?>
<div class="col-sm-9">
    <?php if (! empty($categories)): ?>
        <div class="panel">
            <div class="panel-header main-color-bg">
                <h2>Категории</h2>
            </div>
            <div class="panel-body">
                <?php if (\IhorRadchenko\App\Components\Session::has('errors')): ?>
                    <div class="alert alert-danger error-block">
                        <ul class="text-left">
                            <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                                <?php foreach ($field as $error): ?>
                                    <li><?= $error; ?></li>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
                <?php endif; ?>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Название</th>
                        <th>Кол-во статей</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody class="table-body">
                    <?php foreach ($categories as $category): ?>
                        <tr class="table-row">
                            <td class="firstLetterUC">
                                <a href="/<?= htmlentities($category->link); ?>">
                                    <?= htmlentities(mb_strtolower($category->name)); ?>
                                </a>
                            </td>
                            <td>
                                <?= htmlentities($category->countNews); ?>
                            </td>
                            <td>
                                <button data-id="<?= $category->getId(); ?>" class="btn btn-primary btn-sm btn-update">
                                    Редактировать
                                </button>
                            </td>
                            <td>
                                <button data-id="<?= $category->getId(); ?>" class="btn btn-danger btn-sm btn-delete">Удалить</button>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <?php if (isset($totalPages) && $totalPages > 1): ?>
                    <button class="btn btn-block btn-success" id="moreCategory">ЕЩЕ КАТЕГОРИИ</button>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<div id="forModal"></div>

<?php if (isset($totalPages)): ?>
    <script>
        var totalPages = <?= $totalPages; ?>;
    </script>
<?php endif; ?>

</div>
</div>
</main>