<?php $uri = explode('/', $_SERVER['REQUEST_URI']); ?>
<div class="col-sm-9">
    <?php if (! empty($users)): ?>
        <div class="panel">
            <div class="panel-header main-color-bg">
                <h2>Пользователи</h2>
            </div>
            <div class="panel-body">
                <?php if (\IhorRadchenko\App\Components\Session::has('errors')): ?>
                    <div class="alert alert-danger error-block">
                        <ul class="text-left">
                            <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                                <?php foreach ($field as $error): ?>
                                    <li><?= $error; ?></li>
                                <?php endforeach; ?>
                            <?php endforeach; ?>
                        </ul>
                    </div>
                    <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
                <?php endif; ?>
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th>Имя</th>
                        <th>Email</th>
                        <th>Зарегистрирован</th>
                        <th></th>
                        <th></th>
                    </tr>
                    </thead>
                    <tbody class="table-body">
                    <?php foreach ($users as $user): ?>
                        <tr>
                            <td><?= htmlentities(mb_ucwords($user->getFullName())); ?></td>
                            <td><?= htmlentities($user->email); ?></td>
                            <td><?= $user->formatDate(); ?></td>
                            <td>
                                <button class="btn btn-primary btn-sm btn-update" data-id="<?= $user->getId(); ?>">Редактировать</button>
                            </td>
                            <td>
                                <a href="" class="btn btn-danger btn-sm">Удалить</a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                    </tbody>
                </table>
                <?php if (isset($totalPages) && $totalPages > 1): ?>
                    <button class="btn btn-block btn-success" id="moreUser">ЕЩЕ ПОЛЬЗОВАТЕЛИ</button>
                <?php endif; ?>
            </div>
        </div>
    <?php endif; ?>
</div>

<div id="forModal"></div>

<?php if (isset($totalPages)): ?>
    <script>
        var totalPages = <?= $totalPages; ?>;
    </script>
<?php endif; ?>

</div>
</div>
</main>