<?php
/**
 * Created by PhpStorm.
 * User: Ihor
 * Date: 17.10.2017
 * Time: 16:56
 */

namespace IhorRadchenko\App\Models;

use IhorRadchenko\App\Components\Session;
use IhorRadchenko\App\Components\Traits\File;
use IhorRadchenko\App\DataBase;
use IhorRadchenko\App\Model;

class Brand extends Model
{
    use File;

    const TABLE = 'brands';

    public $name;
    public $description;
    private $logo;

    private $uploadDir = '/public/img/logo/';
    protected $fields = [
        'name' => '',
        'logo' => '',
        'description' => ''
    ];

    public function getLogo(): string
    {
        return '/public/img/logo/' . $this->logo;
    }

    /**
     * @param string $mark
     * @return null
     * @throws \IhorRadchenko\App\Exceptions\DbException
     */
    public static function findOneByMark(string $mark)
    {
        $sql = 'SELECT * FROM ' . self::TABLE . ' WHERE `name` = :mark LIMIT 1';
        $result = DataBase::getInstance()->query($sql, self::class, ['mark' => $mark]);
        return (! empty($result)) ? $result[0] : null;
    }

    /**
     * @param array $data
     * @param array $rules
     * @return bool
     */
    public function load(array $data, array $rules): bool
    {
        if ($data['logo']['error'] === 0) {
            if (! $data['logo'] = $this->loadFile($data['logo'],  'png')) {
                return false;
            }
        } else {
            unset($data['logo']);
        }
        return parent::load($data, $rules); // TODO: Change the autogenerated stub
    }
}