
<div class="col-sm-8 blog-main">
    <?php if (! empty($news)): ?>
        <?php foreach ($news as $article): ?>
            <a href="/<?= htmlentities($article->category->link) . '/' . htmlentities($article->alias); ?>" class="article">
                <span class="articleImg">
                    <img src="<?= htmlentities($article->getImage()); ?>" alt="" class="articlePic">
                </span>
                <span class="article-description">
                    <span class="article-title">
                        <?= htmlentities($article->title); ?>
                    </span>
                    <span class="article-short-text">
                        <?= htmlentities($article->description); ?>
                    </span>
                    <span class="article-date">
                        <?= htmlentities($article->getDate()); ?>
                    </span>
                </span>
            </a>
        <?php endforeach; ?>
    <?php endif; ?>
    <nav class="blog-pagination">
        <?php if (! empty($pagination)): ?>
            <?= $pagination->get(); ?>
        <?php endif; ?>
    </nav>

</div><!-- /.blog-main -->