
<div class="col-sm-8 blog-main">
    <?php foreach ($news as $article): ?>
        <a href="<?= $article->category->link . '/' . $article->getId(); ?>" class="article">
            <span class="articleImg">
                <img src="<?= $article->getImage(); ?>" alt="" class="articlePic">
            </span>
            <span class="article-description">
                <span class="article-title">
                    <?= $article->title; ?>
                </span>
                <span class="article-short-text">
                    <?= $article->description; ?>
                </span>
                <span class="article-date">
                    <?= $article->getDate(); ?>
                </span>
            </span>
        </a>
    <?php endforeach; ?>

</div><!-- /.blog-main -->