
<div class="col-sm-8 blog-main">

    <div class="blog-post">
        <?php if (! empty($car)): ?>
            <div class="post-head">
                <div class="post-header-title">
                    <a href="/">ГЛАВНАЯ</a> |
                    <a href="/mark/<?= htmlentities(mb_strtolower(str_replace(' ', '-', $car->brand->name))); ?>"><?= htmlentities(mb_strtoupper($car->brand->name)); ?></a> |
                    <span><?= htmlentities(mb_strtoupper($car->model)); ?></span>
                </div>
                <img src="<?= htmlentities($car->getImage()); ?>" alt="" class="centerPic">
            </div>
            <div class="blog-post-text">
                <?= IhorRadchenko\App\Components\TextFormat::format(htmlentities($car->text), $car->getId()); ?>
            </div>
        <?php endif; ?>
    </div><!-- /.blog-post -->

    <?php if (! empty($news)): ?>
        <div class="post-mainPage">
            <h1 class="blog-header text-center">Последние новости:</h1>
            <?php foreach ($news as $article): ?>
                <a href="/<?= htmlentities($article->category->link) . '/' . htmlentities($article->alias); ?>" class="article">
            <span class="articleImg">
                <img src="<?= htmlentities($article->getImage()); ?>" alt="" class="articlePic">
            </span>
                    <span class="article-description">
                <span class="article-title">
                    <?= htmlentities($article->title); ?>
                </span>
                <span class="article-short-text">
                    <?= htmlentities($article->description); ?>
                </span>
                <span class="article-date">
                    <?= htmlentities($article->getDate()); ?>
                </span>
            </span>
                </a>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>