<?php $uri = explode('/', $_SERVER['REQUEST_URI']); ?>

<div class="col-sm-8 blog-main">
    <form action="" id="form-reviews" method="post">
        <select name="mark" id="markCar" class="form-control">
            <option value="all">Марка авто</option>
            <?php if (! empty($brands)): ?>
                <?php foreach ($brands as $brand): ?>
                    <option value="<?= htmlentities(mb_strtolower(str_replace(' ', '-', $brand->name))); ?>"
                                    <?php if (isset($uri[3]) && $uri[3] ===
                                    htmlentities(mb_strtolower(str_replace(' ', '-', $brand->name)))) {print 'selected';} ?>
                    >
                        <?= htmlentities(mb_ucwords($brand->name)); ?>
                    </option>
                <?php endforeach; ?>
            <?php endif; ?>
        </select>
        <?php if (! empty($cars)): ?>
            <select name="model" id="modelCar" class="form-control">
                <option value="all">Модель</option>
                <?php foreach ($cars as $car): ?>
                    <option value="<?= htmlentities(mb_strtolower(str_replace(' ', '-', $car->model))); ?>"
                        <?php if (isset($uri[5]) && $uri[5] ===
                            htmlentities(mb_strtolower(str_replace(' ', '-', $car->model)))) {print 'selected';} ?>
                    >
                        <?= htmlentities(mb_ucwords(strtolower($car->model))); ?>
                    </option>
                <?php endforeach; ?>
            </select>
        <?php else: ?>
            <select name="model" id="modelCar" disabled class="form-control">
                <option value="all">Модель</option>
            </select>
        <?php endif; ?>
    </form>
    <?php if (! empty($reviews)): ?>
        <?php foreach ($reviews as $review): ?>
            <div class="review">
                <img src="<?= htmlentities($review->car->getIcon()); ?>" alt="">
                <div class="review-model">
                    <a href="/mark/<?= htmlentities(str_replace(' ', '-', mb_strtolower($review->car->brand->name))) . '/' . htmlentities(str_replace(' ', '-', mb_strtolower($review->car->model))); ?>">
                        <?= htmlentities(mb_strtoupper($review->car->brand->name)) . ' ' . htmlentities(mb_strtoupper($review->car->model)); ?>
                    </a>
                </div>
                <div class="review-rating">
                    <span>&#9733</span> Оценка: <?= htmlentities($review->rating); ?> из 5
                </div>
                <div class="review-content">
                    <div class="review-author">
                        <b><?= htmlentities($review->author->f_name); ?></b>
                        <?php if (! empty($review->author->city)): ?>
                            <b> | <?= htmlentities($review->author->city); ?></b>
                        <?php endif; ?>
                    </div>
                    <div class="review-text">
                        <?= nl2br(htmlentities($review->text)); ?>
                    </div>
                    <div class="review-date">
                        <?= htmlentities($review->getDate()); ?>
                    </div>
                </div>
            </div>
        <?php endforeach; ?>
    <?php else: ?>
        <div class="review-notFound">
            По данному автомобилю отзывов нет...
        </div>
    <?php endif; ?>
    <?php if (\IhorRadchenko\App\Components\Session::has('user')): ?>
        <button class="btn btn-block btn-success" data-toggle="modal" data-target="#addReview">ДОБАВИТЬ ОТЗЫВ</button>
    <?php endif; ?>
</div>

<div class="modal fade" id="addReview" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-addReview" id="addReviewForm" method="post" action="/">
                <div class="modal-header">
                    <h2 class="form-addReview-heading">Ваш отзыв</h2>
                    <button class="close exit-modal" type="button" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">

                    <select class="form-control modal-field" id="selectMark" name="mark" required>
                        <option>Марка</option>
                        <?php if (! empty($brands)): ?>
                            <?php foreach ($brands as $brand): ?>
                                <option value="<?= htmlentities(mb_strtolower(str_replace(' ', '-', $brand->name))); ?>">
                                    <?= htmlentities(mb_ucwords($brand->name)); ?>
                                </option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>

                    <select class="form-control modal-field" id="selectModel" name="model" disabled required>
                        <option>Модель</option>
                    </select>
                    <input type="text" name="f_name" id="inputFName" class="form-control modal-field" placeholder="Имя" required autocomplete="on">
                    <input type="text" name="city" id="inputCity" class="form-control modal-field" placeholder="Город" required autocomplete="on">
                    <textarea name="text" class="form-control modal-field" id="reviewText" rows="10" required placeholder="Текст отзыва"></textarea>
                </div>
                <div class="modal-footer">
                    <input class="btn btn-primary btn-block" type="submit" name="login" value="Отправить">
                </div>
            </form>
        </div>
    </div>
</div>
