<?php $uri = explode('/', $_SERVER['REQUEST_URI']); ?>

<?php if (! empty($totalPage)): ?>
    <script>var totalPage = <?= $totalPage ?>;</script>
<?php endif; ?>

<div class="col-sm-8">
    <div class="blog-main">
        <form action="" id="form-reviews" method="post">
            <select name="mark" id="markCar" class="form-control">
                <option value="all">Марка авто</option>
                <?php if (! empty($brands)): ?>
                    <?php foreach ($brands as $brand): ?>
                        <option value="<?= htmlentities(mb_strtolower(str_replace(' ', '-', $brand->name))); ?>"
                            <?php if (isset($uri[3]) && $uri[3] ===
                                htmlentities(mb_strtolower(str_replace(' ', '-', $brand->name)))) {print 'selected';} ?>
                        >
                            <?= htmlentities(mb_ucwords($brand->name)); ?>
                        </option>
                    <?php endforeach; ?>
                <?php endif; ?>
            </select>
            <?php if (! empty($cars)): ?>
                <select name="model" id="modelCar" class="form-control">
                    <option value="all">Модель</option>
                    <?php foreach ($cars as $car): ?>
                        <option value="<?= htmlentities(mb_strtolower(str_replace(' ', '-', $car->model))); ?>"
                            <?php if (isset($uri[5]) && $uri[5] ===
                                htmlentities(mb_strtolower(str_replace(' ', '-', $car->model)))) {print 'selected';} ?>
                        >
                            <?= htmlentities(mb_ucwords(strtolower($car->model))); ?>
                        </option>
                    <?php endforeach; ?>
                </select>
            <?php else: ?>
                <select name="model" id="modelCar" disabled class="form-control">
                    <option value="all">Модель</option>
                </select>
            <?php endif; ?>
        </form>
        <?php if (! empty($reviews)): ?>
            <?php foreach ($reviews as $review): ?>
                <div class="review">
                    <img src="<?= htmlentities($review->car->getIcon()); ?>" alt="">
                    <div class="review-model">
                        <a href="/mark/<?= htmlentities(str_replace(' ', '-', mb_strtolower($review->car->brand->name))) . '/' . htmlentities(str_replace(' ', '-', mb_strtolower($review->car->model))); ?>">
                            <?= htmlentities(mb_strtoupper($review->car->brand->name)) . ' ' . htmlentities(mb_strtoupper($review->car->model)); ?>
                        </a>
                    </div>
                    <div class="review-rating">
                        <span>&#9733</span> Оценка: <?= htmlentities($review->rating); ?> из 5
                    </div>
                    <div class="review-content">
                        <div class="review-author">
                            <b><?= htmlentities($review->author->f_name); ?></b>
                            <?php if (! empty($review->author->city)): ?>
                                <b> | <?= htmlentities($review->author->city); ?></b>
                            <?php endif; ?>
                        </div>
                        <div class="review-text">
                            <?= nl2br(htmlentities($review->text)); ?>
                        </div>
                        <div class="review-date">
                            <?= htmlentities($review->getDate()); ?>
                        </div>
                    </div>
                </div>
            <?php endforeach; ?>
        <?php else: ?>
            <div class="review-notFound">
                По данному автомобилю отзывов нет...
            </div>
        <?php endif; ?>
    </div>

    <?php if (! empty($reviews) && isset($totalPage) &&$totalPage > 1): ?>
        <button id="btn-moreReview" class="btn btn-block btn-success">ПОКАЗАТЬ БОЛЬШЕ ОТЗЫВОВ</button>
    <?php endif; ?>

    <?php if (\IhorRadchenko\App\Components\Session::has('user')): ?>
        <button id="btn-addReview" class="btn btn-block btn-success" data-toggle="modal" data-target="#addReview">ДОБАВИТЬ ОТЗЫВ</button>
    <?php endif; ?>
</div>

<div class="modal fade" id="addReview" data-backdrop="static">
    <div class="modal-dialog">
        <div class="modal-content">
            <form class="form-addReview" id="addReviewForm" method="post" action="/review/create">
                <div class="modal-header">
                    <h2 class="form-addReview-heading">Ваш отзыв</h2>
                    <button class="close exit-modal" type="button" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                    <?php if (\IhorRadchenko\App\Components\Session::has('add_review') &&
                        \IhorRadchenko\App\Components\Session::get('add_review') === 'fail'): ?>
                        <div class="alert alert-danger error-block">
                            <ul class="text-left">
                                <?php foreach (\IhorRadchenko\App\Components\Session::get('errors') as $field): ?>
                                    <?php foreach ($field as $error): ?>
                                        <li><?= $error; ?></li>
                                    <?php endforeach; ?>
                                <?php endforeach; ?>
                            </ul>
                        </div>
                        <?php \IhorRadchenko\App\Components\Session::delete('errors'); ?>
                    <?php endif; ?>
                    <select class="form-control modal-field" id="selectMark" name="mark" required>
                        <option value="">Марка</option>
                        <?php if (! empty($brands)): ?>
                            <?php foreach ($brands as $brand): ?>
                                <option value="<?= htmlentities(mb_strtolower(str_replace(' ', '-', $brand->name))); ?>">
                                    <?= htmlentities(mb_ucwords($brand->name)); ?>
                                </option>
                            <?php endforeach; ?>
                        <?php endif; ?>
                    </select>

                    <select class="form-control modal-field" id="selectModel" name="model" disabled required>
                        <option>Модель</option>
                    </select>
                    <input type="text" name="f_name" id="inputFName" class="form-control modal-field" placeholder="Имя" required autocomplete="on"
                           value="<?= \IhorRadchenko\App\Components\Session::get('user')->f_name ?? ''; ?>">
                    <input type="text" name="city" id="inputCity" class="form-control modal-field" placeholder="Город" autocomplete="on"
                           value="<?= \IhorRadchenko\App\Components\Session::get('user')->city ?? ''; ?>">
                    <fieldset class="rating">
                        <span class="rating-desc">Оцените модель:</span>
                        <input type="radio" id="star5" name="rating" value="5" /><label class = "full" for="star5" title="Awesome - 5 stars"></label>
                        <input type="radio" id="star4" name="rating" value="4" /><label class = "full" for="star4" title="Pretty good - 4 stars"></label>
                        <input type="radio" id="star3" name="rating" value="3" /><label class = "full" for="star3" title="Meh - 3 stars"></label>
                        <input type="radio" id="star2" name="rating" value="2" /><label class = "full" for="star2" title="Kinda bad - 2 stars"></label>
                        <input required checked type="radio" id="star1" name="rating" value="1" /><label class = "full" for="star1" title="Sucks big time - 1 star"></label>
                    </fieldset>
                    <textarea name="text" class="form-control modal-field" id="reviewText" rows="10" required placeholder="Текст отзыва"></textarea>
                    <input type="hidden" name="token_add_review" value="<?= \IhorRadchenko\App\Components\Token::generate('token_add_review'); ?>">
                </div>
                <div class="modal-footer">
                    <input class="btn btn-primary btn-block" type="submit" name="add_review" value="Отправить">
                </div>
            </form>
        </div>
    </div>
</div>