
<div class="col-sm-12">
    <h1 class="blog-header text-center">ПОИСК</h1>
    <?php if (isset($news)): ?>
        <div class="searchCount">Результатов: <?= count($news); ?></div>
        <div class="blog-post searchList">
            <?php foreach ($news as $article): ?>
                <a class="searchItem" href="/<?= htmlentities($article->category->link) . '/' . htmlentities($article->alias); ?>">
                    <?= htmlentities($article->title); ?>
                </a><br>
            <?php endforeach; ?>
        </div>
    <?php endif; ?>
</div>